dark_mode: dark
output:
  output_format: PNG
  output_height: 32
  output_width: 288
  transparent_bg: true
palettes:
  more_colors: true
  npc_priority: false
tileset:
  default_height: 128
  default_width: 128
  output_sprite_size:
    height: 32
    width: 32
  resize_tileset: true
  resize_to: 128
  sprite_order:
  - 0
  - 12
  - 4
  - 1
  - 3
  - 13
  - 15
  - 5
  - 7
  supported_sizes:
  - height: 256
    resize_to: 128
    width: 256
  - height: 128
    resize_to: 128
    width: 128
  - height: 512
    resize_to: 128
    width: 512
  - height: 1024
    resize_to: 128
    width: 1024
