import { useState, useRef, useEffect } from 'react'
import './TilesetTab.css'
import { DropZone } from '../components/DropZone'
import { useFetch } from '../hooks/useFetch'
import { downloadBlob } from '../utils'
import { Info, X } from 'lucide-react'

const API = '/api'

const FRAME_LABELS = [
  'down idle (standing still)',
  'up idle',
  'left idle',
  'down walk 1 (right foot forward)',
  'down walk 2 (left foot forward)',
  'up walk 1',
  'up walk 2',
  'left walk 1',
  'left walk 2',
]

// ---- Help Modal ----
function HelpModal({ onClose }) {
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-box" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">Overworld sprite format</span>
          <button className="modal-close" onClick={onClose}><X size={16} /></button>
        </div>
        <div className="modal-body">
          <p className="modal-desc">
            Gen 3 overworld sprites are 9-frame spritesheets arranged horizontally.
            The expected frame order is:
          </p>
          <div className="frame-reference">
            {FRAME_LABELS.map((label, i) => (
              <div key={i} className="frame-ref-row">
                <span className="frame-ref-idx">{i}</span>
                <span className="frame-ref-label">{label}</span>
              </div>
            ))}
          </div>
          <p className="modal-note">
            Note: Right-facing frames <b>are not stored</b>, they're generated by <b>horizontally flipping the left-facing frames</b> at runtime.
          </p>
          <div className="modal-examples">
            <p className="section-label">examples</p>
            <div className="example-imgs" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', width: '100%' }}>
              <div className="example-img-wrap" style={{ width: '100%' }}>
                <img src="/example/e4.png" alt="e4 example" className="example-img" draggable={false} style={{ width: '100%', height: 'auto', display: 'block' }} />
                <span className="example-caption">NDS styled sprite</span>
              </div>
              <div className="example-img-wrap" style={{ width: '100%' }}>
                <img src="/example/brendan_walking.png" alt="brendan example" className="example-img" draggable={false} style={{ width: '100%', height: 'auto', display: 'block' }} />
                <span className="example-caption">Brendan walking</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// ---- Output canvas preview ----
function OutputPreview({ tiles, order, tileW, tileH }) {
  const canvasRef = useRef()

  useEffect(() => {
    if (!tiles || tiles.length === 0 || order.length === 0) return
    const canvas = canvasRef.current
    if (!canvas) return

    canvas.width = order.length * tileW
    canvas.height = tileH
    const ctx = canvas.getContext('2d')
    ctx.imageSmoothingEnabled = false
    ctx.clearRect(0, 0, canvas.width, canvas.height)

    order.forEach((idx, pos) => {
      if (idx >= tiles.length) return
      const img = new Image()
      img.onload = () => ctx.drawImage(img, pos * tileW, 0, tileW, tileH)
      img.src = `data:image/png;base64,${tiles[idx]}`
    })
  }, [tiles, order, tileW, tileH])

  if (!tiles || order.length === 0) return null

  return (
    <div className="output-preview-wrap">
      <div className="pixel-scroll">
        <div style={{ position: 'relative', display: 'inline-block' }}>
          <canvas ref={canvasRef} className="output-canvas" style={{ imageRendering: 'pixelated', width: '100%', height: 'auto' }} />
          <svg
            style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' }}
            viewBox={`0 0 ${order.length * tileW} ${tileH}`}
            preserveAspectRatio="none"
          >
            {order.map((_, i) => i > 0 && (
              <line key={i} x1={i * tileW} y1={0} x2={i * tileW} y2={tileH}
                stroke="rgba(255,255,255,0.3)" strokeWidth="0.5" />
            ))}
          </svg>
        </div>
      </div>
      <div className="output-labels">
        {order.map((idx, pos) => (
          <span key={pos} className="output-label">{idx}</span>
        ))}
      </div>
    </div>
  )
}

// ---- Main Tab ----
export function TilesetTab() {
  const [file, setFile] = useState(null)
  const [tileWidth, setTileWidth] = useState(32)
  const [tileHeight, setTileHeight] = useState(32)
  const [spriteOrder, setSpriteOrder] = useState('0,1,2,3,4,5,6,7,8')
  const [result, setResult] = useState(null)
  const [selectedTiles, setSelectedTiles] = useState([])
  const [showHelp, setShowHelp] = useState(false)
  const { loading, error, run } = useFetch()

  const parsedOrder = spriteOrder
    .split(',').map(x => parseInt(x.trim())).filter(x => !isNaN(x))

  const activeOrder = selectedTiles.length > 0 ? selectedTiles : parsedOrder

  const process = async (f, tw, th, order) => {
    const _tw = tw ?? tileWidth
    const _th = th ?? tileHeight
    const _order = order ?? spriteOrder
    const fd = new FormData()
    fd.append('file', f)
    fd.append('tile_width', _tw)
    fd.append('tile_height', _th)
    fd.append('output_width', _order.split(',').filter(Boolean).length * _tw)
    fd.append('output_height', _th)
    fd.append('sprite_order', _order)
    const data = await run(async () => {
      const res = await fetch(`${API}/tileset/process`, { method: 'POST', body: fd })
      if (!res.ok) throw new Error(await res.text())
      return res.json()
    })
    if (data) setResult(data)
  }

  const handleFile = (f) => {
    setFile(f); setResult(null); setSelectedTiles([])
    process(f)
  }

  const handleTileClick = (i) => {
    setSelectedTiles(prev =>
      prev.includes(i) ? prev.filter(x => x !== i) : [...prev, i]
    )
  }

  const handleDownload = async () => {
    if (!file) return
    const order = activeOrder.join(',')
    const fd = new FormData()
    fd.append('file', file)
    fd.append('tile_width', tileWidth)
    fd.append('tile_height', tileHeight)
    fd.append('output_width', activeOrder.length * tileWidth)
    fd.append('output_height', tileHeight)
    fd.append('sprite_order', order)
    await run(async () => {
      const res = await fetch(`${API}/tileset/arrange`, { method: 'POST', body: fd })
      if (!res.ok) throw new Error(await res.text())
      downloadBlob(await res.blob(), `${file.name.replace(/\.[^.]+$/, '')}_arranged.png`)
    })
  }

  return (
    <div className="tab-content">
      {showHelp && <HelpModal onClose={() => setShowHelp(false)} />}

      <div className="tileset-layout">

        {/* left */}
        <div className="tileset-left">
          <DropZone onFile={handleFile} label="Drop tileset image" />

          <div className="field-row">
            <div className="field">
              <label className="field-label">tile w</label>
              <input type="number" className="field-input" value={tileWidth} min={8} max={256}
                onChange={e => setTileWidth(Number(e.target.value))} />
            </div>
            <div className="field">
              <label className="field-label">tile h</label>
              <input type="number" className="field-input" value={tileHeight} min={8} max={256}
                onChange={e => setTileHeight(Number(e.target.value))} />
            </div>
          </div>

          <div className="field">
            <label className="field-label">sprite order</label>
            <input type="text" className="field-input field-mono" value={spriteOrder}
              placeholder="0,1,2,3,4,5,6,7,8"
              onChange={e => setSpriteOrder(e.target.value)} />
          </div>

          <button className="btn-secondary" disabled={!file || loading} onClick={() => process(file)}>
            {loading ? 'processing…' : '↺ re-process'}
          </button>

          {error && <p className="error-msg">{error}</p>}
        </div>

        {/* right */}
        <div className="tileset-right">

          {/* toolbar */}
          <div className="tileset-toolbar">
            <span className="section-label">
              {result
                ? `${result.tile_count} tiles · ${result.tile_width}×${result.tile_height}px`
                : 'no tileset loaded'}
            </span>
            <button className="help-btn" onClick={() => setShowHelp(true)} title="format reference">
              <Info size={15} />
            </button>
          </div>

          {!result && !loading && (
            <div className="empty-state"><p>drop a tileset to slice it into tiles</p></div>
          )}
          {loading && <div className="empty-state"><div className="spinner" /><p>slicing…</p></div>}

          {result && (
            <>
              {/* output preview — live */}
              <div className="tileset-section">
                <div className="section-header">
                  <p className="section-label">
                    output — {selectedTiles.length > 0
                      ? `custom order (${selectedTiles.length} tiles)`
                      : `default order (${parsedOrder.length} tiles)`}
                  </p>
                  <div className="section-actions">
                    {selectedTiles.length > 0 && (
                      <button className="btn-ghost" onClick={() => setSelectedTiles([])}>clear</button>
                    )}
                    <button className="btn-primary-sm" onClick={handleDownload} disabled={loading}>
                      download
                    </button>
                  </div>
                </div>
                <OutputPreview
                  tiles={result.tiles}
                  order={activeOrder}
                  tileW={result.tile_width}
                  tileH={result.tile_height}
                />
              </div>

              {/* tile picker */}
              <div className="tileset-section">
                <p className="section-label">tiles — click to add to arrangement</p>
                <div className="tiles-grid">
                  {result.tiles.map((b64, i) => {
                    const selPos = selectedTiles.indexOf(i)
                    const isSelected = selPos !== -1
                    const isInDefault = parsedOrder.includes(i)
                    return (
                      <div
                        key={i}
                        className={`tile-cell ${isSelected ? 'selected' : ''} ${isInDefault && !isSelected ? 'in-default' : ''}`}
                        data-pos={isSelected ? selPos + 1 : undefined}
                        onClick={() => handleTileClick(i)}
                        title={`tile ${i}`}
                      >
                        <img
                          src={`data:image/png;base64,${b64}`}
                          alt={`tile ${i}`}
                          className="pixel-img tile-img"
                          draggable={false}
                        />
                        <span className="tile-index">
                          {isSelected ? `#${selPos + 1}` : i}
                        </span>
                      </div>
                    )
                  })}
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  )
}