import { useState, useEffect } from 'react'
import './TilesetTab.css'
import { DropZone } from '../components/DropZone'
import { Modal } from '../components/Modal'
import { useFetch } from '../hooks/useFetch'
import { downloadBlob } from '../utils'
import { Info, X, Save, Download } from 'lucide-react'
import { PresetList } from '../components/PresetList'

const API = '/api'

const OW_LABELS = [
  'down idle','up idle','left idle',
  'down walk 1','down walk 2',
  'up walk 1','up walk 2',
  'left walk 1','left walk 2',
]

function useDebounce(value, delay) {
  const [d, setD] = useState(value)
  useEffect(() => {
    const t = setTimeout(() => setD(value), delay)
    return () => clearTimeout(t)
  }, [value, delay])
  return d
}

// ---------------------------------------------------------------------------
// Help modal
// ---------------------------------------------------------------------------
function HelpModal({ onClose }) {
  return (
    <Modal title="Overworld sprite format" onClose={onClose}>
      <p className="modal-desc">Gen 3 overworld sprites are 9-frame spritesheets arranged horizontally:</p>
      <div className="frame-reference">
        {OW_LABELS.map((label, i) => (
          <div key={i} className="frame-ref-row">
            <span className="frame-ref-idx">{i}</span>
            <span className="frame-ref-label">{label}</span>
          </div>
        ))}
      </div>
      <p className="modal-note">Right-facing frames are generated by flipping left-facing frames at runtime.</p>
      <div className="modal-examples">
        <p className="section-label" style={{ marginBottom: 8 }}>examples</p>
        <div className="example-imgs">
          <div className="example-img-wrap">
            <img src="/img/help/tileset/cynthia.png" alt="NDS styled sprite" className="example-img" draggable={false}/>
            <span className="example-caption">cynthia.png</span>
          </div>
          <div className="example-img-wrap">
            <img src="/img/help/tileset/may.png" alt="GBA styled sprite" className="example-img" draggable={false}/>
            <span className="example-caption">may.png</span>
          </div>
        </div>
      </div>
    </Modal>
  )
}

// ---------------------------------------------------------------------------
// Save preset modal
// ---------------------------------------------------------------------------
function SaveModal({ onSave, onClose }) {
  const [name, setName] = useState('')
  const [id, setId]     = useState('')
  return (
    <Modal title="save preset" onClose={onClose} size="sm">
      <div className="field">
        <label className="field-label">name</label>
        <input className="field-input" value={name}
          onChange={e => {
            setName(e.target.value)
            setId(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,''))
          }}
          placeholder="My custom preset" />
      </div>
      <div className="field">
        <label className="field-label">id</label>
        <input className="field-input field-mono" value={id}
          onChange={e => setId(e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g,''))}
          placeholder="my_custom_preset" />
      </div>
      <button className="btn-primary" disabled={!name || !id} onClick={() => onSave(id, name)}>save</button>
    </Modal>
  )
}

// ---------------------------------------------------------------------------
// Source sheet with tile grid overlay
// ---------------------------------------------------------------------------
function SourceSheet({ b64, sourceW, sourceH, tileW, tileH, selectedTile, onTileClick }) {
  if (!b64) return null
  const cols  = Math.max(1, Math.floor(sourceW / tileW))
  const rows  = Math.max(1, Math.floor(sourceH / tileH))
  return (
    <div className="source-sheet-wrap">
      <div className="source-grid-container">
        <img src={`data:image/png;base64,${b64}`} alt="source" className="source-img" draggable={false}/>
        <div className="source-tile-grid" style={{ '--src-cols': cols, '--src-rows': rows }}>
          {Array.from({ length: cols * rows }).map((_, idx) => (
            <div
              key={idx}
              className={`source-tile ${selectedTile === idx ? 'selected' : ''}`}
              onClick={() => onTileClick(idx)}
              title={`tile ${idx}`}
            />
          ))}
        </div>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Output slot grid
// ---------------------------------------------------------------------------
function OutputGrid({ slots, setSlots, cols, rows, tiles, selectedTile, setSelectedTile, slotLabels }) {
  const handleSlotClick = (idx) => {
    if (selectedTile !== null) {
      setSlots(prev => { const s = [...prev]; s[idx] = selectedTile; return s })
      setSelectedTile(null)
    } else if (slots[idx] != null) {
      setSelectedTile(slots[idx])
      setSlots(prev => { const s = [...prev]; s[idx] = null; return s })
    }
  }
  const clearSlot = (e, idx) => {
    e.stopPropagation()
    setSlots(prev => { const s = [...prev]; s[idx] = null; return s })
  }
  const canPlace = selectedTile !== null
  return (
    <div className="output-grid" style={{ '--cols': cols }}>
      {Array.from({ length: cols * rows }).map((_, idx) => {
        const tileIdx = slots[idx]
        const hasTile = tileIdx != null
        const label   = slotLabels?.[idx] ?? String(idx)
        return (
          <div
            key={idx}
            className={`output-slot ${hasTile ? 'filled' : 'empty'} ${canPlace && !hasTile ? 'droppable' : ''}`}
            onClick={() => handleSlotClick(idx)}
          >
            {hasTile && tiles?.[tileIdx]
              ? <img src={`data:image/png;base64,${tiles[tileIdx]}`} alt={label} className="slot-img" draggable={false}/>
              : <span className="slot-plus">+</span>
            }
            <span className="slot-label">{label}</span>
            {hasTile && (
              <button className="slot-clear" onClick={e => clearSlot(e, idx)}><X size={9}/></button>
            )}
          </div>
        )
      })}
    </div>
  )
}

// ---------------------------------------------------------------------------
// Download via backend so indexed PNG metadata can be preserved
// ---------------------------------------------------------------------------
async function buildAndDownload(sourceFile, slots, cols, rows, inputTileW, inputTileH, outputTileW, outputTileH, filename) {
  if (!sourceFile) throw new Error('No tileset source available')

  const fd = new FormData()
  fd.append('file', sourceFile)
  fd.append('input_tile_width', String(inputTileW))
  fd.append('input_tile_height', String(inputTileH))
  fd.append('output_tile_width', String(outputTileW))
  fd.append('output_tile_height', String(outputTileH))
  fd.append('cols', String(cols))
  fd.append('rows', String(rows))
  fd.append('sprite_order', slots.map(tileIdx => (tileIdx == null ? '' : String(tileIdx))).join(','))

  const res = await fetch(`${API}/tileset/arrange`, { method: 'POST', body: fd })
  if (!res.ok) throw new Error(await res.text())

  const blob = await res.blob()
  downloadBlob(blob, filename)
}

// ---------------------------------------------------------------------------
// Main tab
// ---------------------------------------------------------------------------
export function TilesetTab() {
  const [file, setFile]         = useState(null)
  const [arrangeFile, setArrangeFile] = useState(null)
  const [outputName, setOutputName] = useState('')
  // Source tile size (how big tiles are in the uploaded image)
  const [inTileW, setInTileW]   = useState(32)
  const [inTileH, setInTileH]   = useState(32)
  // Output tile size (what size tiles should be in the result)
  const [outTileW, setOutTileW] = useState(32)
  const [outTileH, setOutTileH] = useState(32)
  const [cols, setCols]         = useState(9)
  const [rows, setRows]         = useState(1)
  const [slotLabels, setSlotLabels] = useState([])

  const [result, setResult]               = useState(null)
  const [slots, setSlots]                 = useState(Array(9).fill(null))
  const [selectedTile, setSelectedTile]   = useState(null)
  const [showHelp, setShowHelp]           = useState(false)
  const [showSave, setShowSave]           = useState(false)
  const [presets, setPresets]             = useState([])
  const [activePresetId, setActivePresetId] = useState(null)
  const [defaultIds, setDefaultIds]       = useState(new Set())
  const [downloadError, setDownloadError] = useState(null)
  const [downloading, setDownloading]     = useState(false)
  const { loading, error, run }           = useFetch()

  // Debounce everything that triggers a re-slice
  const dInW  = useDebounce(inTileW,  500)
  const dInH  = useDebounce(inTileH,  500)
  const dOutW = useDebounce(outTileW, 500)
  const dOutH = useDebounce(outTileH, 500)

  const fetchPresets = () =>
    fetch(`${API}/presets`).then(r => r.json()).then(p => {
      setPresets(p)
      setDefaultIds(new Set(p.filter(x => x.is_default).map(x => x.id)))
    }).catch(() => {})

  useEffect(() => { fetchPresets() }, [])

  useEffect(() => {
    if (file) doSlice(file, dInW, dInH, dOutW, dOutH)
  }, [dInW, dInH, dOutW, dOutH])

  const resetSlots = (c, r) => setSlots(Array(c * r).fill(null))

  // ---------------------------------------------------------------------------
  // Slice on the backend so paletted PNG metadata can be preserved
  // ---------------------------------------------------------------------------
  const doSlice = async (f, iw, ih, ow, oh) => {
    setArrangeFile(f)

    const fd = new FormData()
    fd.append('file', f)
    fd.append('input_tile_width', String(iw))
    fd.append('input_tile_height', String(ih))
    fd.append('output_tile_width', String(ow))
    fd.append('output_tile_height', String(oh))

    const data = await run(async () => {
      const res = await fetch(`${API}/tileset/slice`, { method: 'POST', body: fd })
      if (!res.ok) throw new Error(await res.text())
      return res.json()
    })
    if (data) { setResult(data); setSelectedTile(null) }
  }

  const handleFile = (f) => {
    setFile(f); setArrangeFile(f); setResult(null); resetSlots(cols, rows); setDownloadError(null)
    setOutputName(`${f.name.replace(/\.[^.]+$/, '')}_arranged`)
    doSlice(f, inTileW, inTileH, outTileW, outTileH)
  }

  const handleColsChange = (v) => { setCols(v); resetSlots(v, rows) }
  const handleRowsChange = (v) => { setRows(v); resetSlots(cols, v) }

  // Sync outTileW/H when in changes (unless user has already diverged them)
  const handleInTileW = (v) => {
    if (inTileW === outTileW) setOutTileW(v)
    setInTileW(v)
  }
  const handleInTileH = (v) => {
    if (inTileH === outTileH) setOutTileH(v)
    setInTileH(v)
  }

  // ---------------------------------------------------------------------------
  // Presets
  // ---------------------------------------------------------------------------
  const handleLoadPreset = async (id) => {
    const p = await fetch(`${API}/presets/${id}`).then(r => r.json())
    setInTileW(p.tile_w);   setInTileH(p.tile_h)
    setOutTileW(p.out_tile_w ?? p.tile_w)
    setOutTileH(p.out_tile_h ?? p.tile_h)
    setCols(p.cols);         setRows(p.rows)
    setSlots(p.slots?.length === p.cols * p.rows ? p.slots : Array(p.cols * p.rows).fill(null))
    setSlotLabels(p.slot_labels || [])
    setActivePresetId(id)
    if (file) doSlice(file, p.tile_w, p.tile_h, p.out_tile_w ?? p.tile_w, p.out_tile_h ?? p.tile_h)
  }

  const handleSavePreset = async (id, name) => {
    const srcCols = result ? Math.floor(result.source_w / result.input_tile_width)  : undefined
    const srcRows = result ? Math.floor(result.source_h / result.input_tile_height) : undefined
    const body = {
      name,
      tile_w:     inTileW,
      tile_h:     inTileH,
      out_tile_w: outTileW,
      out_tile_h: outTileH,
      cols, rows, slots,
      slot_labels: slotLabels.length ? slotLabels : undefined,
      src_cols:   srcCols,
      src_rows:   srcRows,
    }
    await fetch(`${API}/presets/${id}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    fetchPresets(); setActivePresetId(id); setShowSave(false)
  }

  const handleDeletePreset = async (id) => {
    if (defaultIds.has(id)) return
    await fetch(`${API}/presets/${id}`, { method: 'DELETE' })
    fetchPresets()
    if (activePresetId === id) setActivePresetId(null)
  }

  const needsScale  = inTileW !== outTileW || inTileH !== outTileH
  const scaleLabel  = needsScale
    ? `${inTileW}×${inTileH} → ${outTileW}×${outTileH}`
    : `${outTileW}×${outTileH}px`

  const handleDownload = async () => {
    if (!result || !arrangeFile || slots.every(s => s == null) || !outputName.trim()) return
    setDownloadError(null)
    setDownloading(true)
    try {
      await buildAndDownload(
        arrangeFile, slots, cols, rows,
        result.input_tile_width, result.input_tile_height,
        result.tile_width, result.tile_height,
        `${outputName.trim()}.png`,
      )
    } catch (e) {
      setDownloadError(e.message || 'Failed to download arranged tileset')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="tab-content">
      {showHelp && <HelpModal onClose={() => setShowHelp(false)}/>}
      {showSave && <SaveModal onSave={handleSavePreset} onClose={() => setShowSave(false)}/>}

      <div className="tileset-layout">

        {/* ── Left panel ── */}
        <div className="tileset-left">
          <DropZone onFile={handleFile} label="Drop tileset image"/>

          {file && (
            <div className="field">
              <label className="field-label">output name</label>
              <input
                className="field-input"
                value={outputName}
                onChange={e => setOutputName(e.target.value)}
                spellCheck={false}
                placeholder="sprite_arranged"
              />
              <span className="tileset-field-hint">used for the downloaded PNG filename</span>
            </div>
          )}

          {/* Tile dimensions */}
          <div className="tile-dim-grid">
            <span className="tile-dim-label">input tile</span>
            <input type="number" className="field-input" min={1} max={512}
              value={inTileW} onChange={e => handleInTileW(Number(e.target.value))}/>
            <span className="tile-dim-sep">×</span>
            <input type="number" className="field-input" min={1} max={512}
              value={inTileH} onChange={e => handleInTileH(Number(e.target.value))}/>

            <span className="tile-dim-label">output tile</span>
            <input type="number" className={`field-input ${needsScale ? 'field-input--accent' : ''}`}
              min={1} max={512}
              value={outTileW} onChange={e => setOutTileW(Number(e.target.value))}/>
            <span className="tile-dim-sep">×</span>
            <input type="number" className={`field-input ${needsScale ? 'field-input--accent' : ''}`}
              min={1} max={512}
              value={outTileH} onChange={e => setOutTileH(Number(e.target.value))}/>
          </div>

          {/* Quick scale buttons — only shown when tiles differ */}
          {needsScale && (
            <div className="tile-quick-row">
              {[0.25, 0.5, 1, 2, 4].map(f => (
                <button key={f} className="tile-quick-btn"
                  onClick={() => { setOutTileW(Math.max(1,Math.round(inTileW*f))); setOutTileH(Math.max(1,Math.round(inTileH*f))) }}>
                  {f < 1 ? `${f}×` : `${f}×`}
                </button>
              ))}
              <button className="tile-quick-btn tile-quick-btn--reset"
                onClick={() => { setOutTileW(inTileW); setOutTileH(inTileH) }}>
                reset
              </button>
            </div>
          )}

          {/* Cols / rows */}
          <div className="tile-dim-grid">
            <span className="tile-dim-label">cols</span>
            <input type="number" className="field-input" min={1} max={32}
              value={cols} onChange={e => handleColsChange(Number(e.target.value))}/>
            <span className="tile-dim-sep"/>
            <span/>

            <span className="tile-dim-label">rows</span>
            <input type="number" className="field-input" min={1} max={32}
              value={rows} onChange={e => handleRowsChange(Number(e.target.value))}/>
            <span className="tile-dim-sep"/>
            <span/>
          </div>

          {/* Presets */}
          <div className="preset-section">
            <p className="section-label">presets</p>
            <PresetList
              presets={presets}
              defaultIds={defaultIds}
              activePresetId={activePresetId}
              onLoad={handleLoadPreset}
              onDelete={handleDeletePreset}
              currentState={{ tileW: inTileW, tileH: inTileH, cols, rows, slots }}
            />
            <button className="btn-secondary preset-save-btn" onClick={() => setShowSave(true)}>
              <Save size={12}/> save as preset
            </button>
          </div>

          {(error || downloadError) && <p className="error-msg">{downloadError || error}</p>}

          {/* Source preview */}
          {result && (
            <div className="source-section">
              <p className="section-label">
                source — {result.tile_count} tiles
                {selectedTile !== null
                  ? <span className="selected-hint"> · {selectedTile} selected</span>
                  : <span className="selected-hint"> · click to select</span>
                }
              </p>
              <SourceSheet
                b64={result.source}
                sourceW={result.source_w}
                sourceH={result.source_h}
                tileW={result.input_tile_width}
                tileH={result.input_tile_height}
                selectedTile={selectedTile}
                onTileClick={i => setSelectedTile(prev => prev === i ? null : i)}
              />
            </div>
          )}
        </div>

        {/* ── Right panel ── */}
        <div className="tileset-right">
          <div className="tileset-toolbar">
            <span className="section-label">
              {result ? `output — ${cols}×${rows} · ${scaleLabel}` : 'no tileset loaded'}
            </span>
            <div style={{ display: 'flex', gap: 6 }}>
              {result && <>
                <button className="btn-ghost" onClick={() => resetSlots(cols, rows)}>clear</button>
              </>}
              <button className="tab-help-btn" onClick={() => setShowHelp(true)} title="Help"><Info size={15}/></button>
            </div>
          </div>

          {!result && !loading && <div className="empty-state"><p>drop a tileset to start arranging</p></div>}
          {loading && <div className="empty-state"><div className="spinner"/><p>slicing…</p></div>}

          {result && (
            <>
              {selectedTile !== null && (
                <div className="place-hint">
                  tile {selectedTile} selected — click a slot to place it
                  <button className="btn-ghost" onClick={() => setSelectedTile(null)}>cancel</button>
                </div>
              )}
              <div className="tileset-output-stack">
                <OutputGrid
                  slots={slots} setSlots={setSlots}
                  cols={cols} rows={rows}
                  tiles={result.tiles}
                  selectedTile={selectedTile} setSelectedTile={setSelectedTile}
                  slotLabels={slotLabels}
                />
                <button
                  className="btn-primary tileset-download-btn"
                  disabled={slots.every(s => s == null) || !outputName.trim() || downloading}
                  onClick={handleDownload}
                >
                  <Download size={13} />
                  {downloading ? 'downloading…' : `Download '${outputName.trim()}.png'`}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
